kind: PersistentVolume     
apiVersion: v1
metadata:
  name: pv-volume-rabbitmq01   
  labels:
    type: local
    app.kubernetes.io/component: rabbitmq
    app.kubernetes.io/name: production-rabbitmqcluster
    app.kubernetes.io/part-of: rabbitmq            
spec:
  capacity:
    storage: 30G           
  accessModes:
    - ReadWriteOnce        
  hostPath:                
    path: "/data/rabbitmq/"      
---
kind: PersistentVolume     
apiVersion: v1
metadata:
  name: pv-volume-rabbitmq02   
  labels:
    type: local
    app.kubernetes.io/component: rabbitmq
    app.kubernetes.io/name: production-rabbitmqcluster
    app.kubernetes.io/part-of: rabbitmq            
spec:
  capacity:
    storage: 30G           
  accessModes:
    - ReadWriteOnce        
  hostPath:                
    path: "/data/rabbitmq/"   
---
kind: PersistentVolume     
apiVersion: v1
metadata:
  name: pv-volume-rabbitmq03   
  labels:
    type: local
    app.kubernetes.io/component: rabbitmq
    app.kubernetes.io/name: production-rabbitmqcluster
    app.kubernetes.io/part-of: rabbitmq            
spec:
  capacity:
    storage: 30G           
  accessModes:
    - ReadWriteOnce        
  hostPath:                
    path: "/data/rabbitmq/"   
  